"""Chat panel with welcome/empty state, styled citation badges, and cleaner messages."""

from __future__ import annotations

import re
from html import escape
from typing import Any

import streamlit as st

from src.agents.graph import get_app, initial_state
from src.ui.components.trace_view import render_trace
from src.ui.session import get_messages
from src.ui.styles import html
from src.utils.logging import get_logger

log = get_logger(__name__)


_UUID_RE = re.compile(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")


_EXAMPLE_PROMPTS = [
    ("text", "What is this document about?"),
    ("text", "What datasets does the paper evaluate on?"),
    ("image", "Describe the image I attached."),
    ("cross_modal", "Does the attached chart match the paper's reported trends?"),
]


def _render_welcome() -> None:
    tiles = "".join(
        (
            '<div class="prompt">'
            f'<span class="route-tag">{route}</span>'
            f'<div>{escape(text)}</div>'
            "</div>"
        )
        for route, text in _EXAMPLE_PROMPTS
    )
    html(
        f"""
        <div class="vra-welcome">
          <h3>Upload a PDF in the sidebar to begin.</h3>
          <p>Optionally attach an image to ask cross-modal questions. Every answer
          is generated by a multi-agent LangGraph pipeline and reviewed by an
          independent critic before it reaches you.</p>
          <div class="prompts">{tiles}</div>
        </div>
        """
    )


def _stylize_citations(answer: str, citations: list[str]) -> str:
    """Replace raw UUIDs (citations) with badge-styled spans."""
    citation_set = set(citations)

    def _sub(match: re.Match) -> str:
        uid = match.group(0)
        short = uid[:8]
        cls = "vra-cite"
        if citation_set and uid in citation_set:
            return f'<span class="{cls}" title="{uid}">{short}</span>'
        return f'<span class="{cls}" title="{uid}">{short}</span>'

    return _UUID_RE.sub(_sub, answer)


def _escape_and_style(answer: str, citations: list[str]) -> str:
    safe = escape(answer or "")
    # Re-apply citation styling on the escaped string (UUIDs are ASCII so escape is safe).
    styled = _stylize_citations(safe, citations)
    # Keep line breaks.
    return styled.replace("\n", "<br>")


def _render_assistant_message(msg: dict[str, Any]) -> None:
    answer = msg.get("content", "")
    citations = msg.get("citations") or []
    styled = _escape_and_style(answer, citations)
    html(f'<div style="font-size: 14px; line-height: 1.6;">{styled}</div>')
    if msg.get("degraded"):
        html(
            '<div class="vra-degraded">⚠ The critic flagged a possible hallucination '
            "and the retry did not resolve it. Treat this answer with caution.</div>"
        )
    if msg.get("trace"):
        render_trace(msg["trace"], mermaid_src=msg.get("mermaid"))


def _render_history() -> None:
    msgs = get_messages()
    if not msgs:
        _render_welcome()
        return
    for msg in msgs:
        with st.chat_message(msg["role"]):
            if msg["role"] == "assistant":
                _render_assistant_message(msg)
            else:
                st.markdown(msg["content"])


def _run_graph(session_id: str, question: str, user_image_b64: str | None) -> dict[str, Any]:
    app = get_app()
    config = {"configurable": {"thread_id": f"{session_id}-{hash(question) & 0xffff}"}}
    state = initial_state(session_id, question, user_image_b64)
    final_state: dict[str, Any] = {}
    for event in app.stream(state, config=config, stream_mode="values"):
        final_state = event
    return final_state


def _get_mermaid() -> str | None:
    try:
        return get_app().get_graph().draw_mermaid()
    except Exception as exc:
        log.debug("mermaid_unavailable", error=str(exc))
        return None


def render_chat(session_id: str) -> None:
    _render_history()

    question = st.chat_input("Ask a question about the document and/or the attached image…")
    if not question:
        return

    user_image_b64 = st.session_state.get("user_image_b64")

    get_messages().append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Agents thinking…"):
            try:
                final = _run_graph(session_id, question, user_image_b64)
            except Exception as exc:
                log.exception("graph_run_failed", error=str(exc))
                st.error(f"Agent graph failed: {exc}")
                return

        answer = final.get("answer") or "(no answer produced)"
        citations = final.get("citations") or []
        degraded = final.get("degraded", False)
        trace = final.get("trace", [])
        mermaid = _get_mermaid()

        styled = _escape_and_style(answer, citations)
        html(f'<div style="font-size: 14px; line-height: 1.6;">{styled}</div>')
        if degraded:
            html(
                '<div class="vra-degraded">⚠ The critic flagged a possible hallucination '
                "and the retry did not resolve it. Treat this answer with caution.</div>"
            )
        render_trace(trace, mermaid_src=mermaid)

        get_messages().append(
            {
                "role": "assistant",
                "content": answer,
                "citations": citations,
                "degraded": degraded,
                "trace": trace,
                "mermaid": mermaid,
            }
        )
